let data=[
  {
    title: "Software Engineering Intern",
    description: "Join our dynamic team to develop scalable web applications.",
    requirement: "Basic knowledge of JavaScript, Node.js, and React.",
    location: "Remote",
    internshiptype: "paid",
    stipend: 1500,
    openings: 3,
    owner:"683014858662722019fa93a3",
  },
  {
    title: "Marketing Intern",
    description: "Assist with digital marketing campaigns and social media outreach.",
    requirement: "Strong communication skills and familiarity with social media platforms.",
    location: "New York",
    internshiptype: "unpaid",
    stipend: 0,
    openings: 1,
    owner:"683014858662722019fa93a3",
  },
  {
    title: "Data Science Intern",
    description: "Analyze large datasets and build predictive models.",
    requirement: "Experience with Python, SQL, and machine learning basics.",
    location: "San Francisco",
    internshiptype: "paid",
    stipend: 2000,
    openings: 2,
    owner:"6830149c8662722019fa93ac",
  },
  {
    title: "Content Writing Intern",
    description: "Create engaging blog posts and articles for our website.",
    requirement: "Excellent writing skills and attention to detail.",
    location: "Chicago",
    internshiptype: "unpaid",
    stipend: 0,
    openings: 2,
    owner:"6830149c8662722019fa93ac",
  
  },
  {
    title: "Graphic Design Intern",
    description: "Design visual content for digital and print media.",
    requirement: "Proficiency in Photoshop, Illustrator, and a strong design sense.",
    location: "Los Angeles",
    internshiptype: "paid",
    stipend: 1000,
    openings: 1,
    owner:"683014b78662722019fa93b5",
  },
  {
    title: "Cybersecurity Intern",
    description: "Help secure our systems and identify vulnerabilities.",
    requirement: "Understanding of network security and ethical hacking basics.",
    location: "Austin",
    internshiptype: "paid",
    stipend: 1800,
    openings: 2,
    owner:"683014b78662722019fa93b5"
  },
  {
    title: "HR Intern",
    description: "Assist in recruitment and employee engagement initiatives.",
    requirement: "Good interpersonal skills and basic HR knowledge.",
    location: "Seattle",
    internshiptype: "unpaid",
    stipend: 0,
    openings: 1,
    owner:"683014d28662722019fa93be",
  },
  {
    title: "Finance Intern",
    description: "Support financial analysis and budgeting activities.",
    requirement: "Strong analytical skills and proficiency in Excel.",
    location: "Boston",
    internshiptype: "paid",
    stipend: 1200,
    openings: 1,
    owner:"683014d28662722019fa93be",
  },
  {
    title: "AI Intern",
    description: "Contribute to AI projects through data analysis and model training.",
    requirement: "Experience with Python and machine learning frameworks.",
    location: "San Jose",
    internshiptype: "paid",
    stipend: 2500,
    openings: 2,
    owner:"683014e78662722019fa93c7",
  },
  {
    title: "Full-Stack Intern",
    description: "Work on both front-end and back-end development tasks.",
    requirement: "Proficiency in HTML, CSS, JavaScript, and a backend language.",
    location: "Remote",
    internshiptype: "paid",
    stipend: 2000,
    openings: 3,
    owner:"683014e78662722019fa93c7",
  },
  {
    title: "Customer Support Intern",
    description: "Assist customers via email and chat support.",
    requirement: "Excellent communication skills and problem-solving mindset.",
    location: "Denver",
    internshiptype: "unpaid",
    stipend: 0,
    openings: 2,
    owner:"683014fa8662722019fa93d0",
  },
  {
    title: "Event Management Intern",
    description: "Help plan and coordinate company events.",
    requirement: "Strong organizational skills and experience in event planning.",
    location: "Miami",
    internshiptype: "unpaid",
    stipend: 0,
    openings: 1,
    owner:"683014fa8662722019fa93d0",
  },
  {
    title: "Machine Learning Intern",
    description: "Develop and fine-tune machine learning algorithms.",
    requirement: "Knowledge of Python, TensorFlow, and data processing.",
    location: "Palo Alto",
    internshiptype: "paid",
    stipend: 2200,
    openings: 2,
    owner:"683015178662722019fa93d9",
  },
  {
    title: "Legal Intern",
    description: "Assist with legal research and documentation.",
    requirement: "Understanding of legal concepts and strong research skills.",
    location: "Washington D.C.",
    internshiptype: "unpaid",
    stipend: 0,
    openings: 1,
    owner:"683015178662722019fa93d9",
  },
  {
    title: "E-commerce Intern",
    description: "Support online store operations and digital marketing.",
    requirement: "Basic understanding of e-commerce platforms and social media.",
    location: "San Diego",
    internshiptype: "paid",
    stipend: 1300,
    openings: 2,
    owner:"683015328662722019fa93e2",
 
  },
  {
    title: "Mobile App Intern",
    description: "Assist in mobile application development and testing.",
    requirement: "Experience with Android or iOS development tools.",
    location: "Toronto",
    internshiptype: "paid",
    stipend: 1600,
    openings: 1,
    owner:"683015328662722019fa93e2",

  },
  {
    title: "Social Media Intern",
    description: "Manage and create content for social media channels.",
    requirement: "Familiarity with social networks and basic graphic design skills.",
    location: "Los Angeles",
    internshiptype: "unpaid",
    stipend: 0,
    openings: 1,
    owner:"6830154d8662722019fa93eb",

  },
  {
    title: "Business Analyst Intern",
    description: "Analyze business processes and aid in strategic planning.",
    requirement: "Strong analytical skills and attention to detail.",
    location: "Chicago",
    internshiptype: "paid",
    stipend: 1400,
    openings: 2,
    owner:"6830154d8662722019fa93eb",
  },
  {
    title: "Product Management Intern",
    description: "Work with product and design teams to develop strategies.",
    requirement: "Excellent communication and problem-solving skills.",
    location: "Austin",
    internshiptype: "paid",
    stipend: 1700,
    openings: 1,
    owner:"6830154d8662722019fa93eb",
   
  },
  {
    title: "Research Intern",
    description: "Assist with academic or market research projects.",
    requirement: "Strong research skills and familiarity with data analysis.",
    location: "Boston",
    internshiptype: "unpaid",
    stipend: 0,
    openings: 1,
    owner:"6830156f8662722019fa93f4",

  },
  {
    title: "R&D Intern",
    description: "Contribute to research and development efforts in our innovation lab.",
    requirement: "Creative thinking and basic understanding of research methodologies.",
    location: "Seattle",
    internshiptype: "paid",
    stipend: 1900,
    openings: 2,
    owner:"6830156f8662722019fa93f4",
  }
];


module.exports=data;
